name: docker

on:
  push:
    branches: [ main, develop ]
    tags: "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  docker:
    strategy:
      matrix:
        include:
          - dockerFilename: Dockerfile
            imageName: ktwrd/xenia-discord
          - dockerFilename: Dockerfile
            imageName: ghcr.io/ktwrd/xenia-discord
          - dockerFilename: WebPanel.Dockerfile
            imageName: ktwrd/xenia-discord-dash
          - dockerFilename: WebPanel.Dockerfile
            imageName: ghcr.io/ktwrd/xenia-discord-dash
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Environment Variables
        run: |
          echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          echo "CONTAINER_VERSION=$(git describe --tags --abbrev=0).$([[ $GITHUB_REF = refs/tags/* ]] && echo 0 || echo 65534)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "REVISION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date --iso-8601=s)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push (dev, ${{ matrix.imageName }}, ${{ matrix.dockerFilename }})'
        uses: docker/build-push-action@v5
        if: github.ref == 'refs/heads/develop'
        with:
          push: true
          tags: |
            ${{ matrix.imageName }}:dev
            ${{ matrix.imageName }}:latest
            ${{ matrix.imageName }}:dev-${{ env.CONTAINER_VERSION }}
            ${{ matrix.imageName }}:latest-${{ env.CONTAINER_VERSION }}
          file: ${{ matrix.dockerFilename }}

      - name: 'Build and push (stable, ${{ matrix.imageName }}, ${{ matrix.dockerFilename }})'
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ matrix.imageName }}:${{ env.TAG }}
            ${{ matrix.imageName }}:${{ env.CONTAINER_VERSION }}
            ${{ matrix.imageName }}:stable
            ${{ matrix.imageName }}:stable-${{ env.CONTAINER_VERSION }}
          file: ${{ matrix.dockerFilename }}